// <auto-generated />
using System;
using AyalasLanguageAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AyalasLanguageAPI.Data.Migrations.SQLite
{
    [DbContext(typeof(AyalasLanguageDbContext))]
    partial class AyalasLanguageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnownLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciseId");

                    b.HasIndex("ExerciseTypeId");

                    b.HasIndex("KnownLanguageId");

                    b.HasIndex("LearningPathId");

                    b.HasIndex("TargetLanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.ExerciseType", b =>
                {
                    b.Property<int>("ExerciseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ExerciseTypeId");

                    b.ToTable("ExerciseTypes");

                    b.HasData(
                        new
                        {
                            ExerciseTypeId = 1,
                            Name = "from Known to target language"
                        },
                        new
                        {
                            ExerciseTypeId = 2,
                            Name = "from target to Known language"
                        },
                        new
                        {
                            ExerciseTypeId = 3,
                            Name = "Fill in the Blank"
                        },
                        new
                        {
                            ExerciseTypeId = 4,
                            Name = "Matching"
                        },
                        new
                        {
                            ExerciseTypeId = 5,
                            Name = "from Known to target language - bucket list"
                        });
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRightToLeft")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            Code = "en",
                            EnglishName = "English",
                            IsRightToLeft = false,
                            NativeName = "English"
                        },
                        new
                        {
                            LanguageId = 2,
                            Code = "ar",
                            EnglishName = "Arabic",
                            IsRightToLeft = true,
                            NativeName = "العربية"
                        },
                        new
                        {
                            LanguageId = 3,
                            Code = "da",
                            EnglishName = "Danish",
                            IsRightToLeft = false,
                            NativeName = "Dansk"
                        },
                        new
                        {
                            LanguageId = 4,
                            Code = "es",
                            EnglishName = "Spanish",
                            IsRightToLeft = false,
                            NativeName = "Español"
                        },
                        new
                        {
                            LanguageId = 5,
                            Code = "fr",
                            EnglishName = "French",
                            IsRightToLeft = false,
                            NativeName = "Français"
                        },
                        new
                        {
                            LanguageId = 6,
                            Code = "de",
                            EnglishName = "German",
                            IsRightToLeft = false,
                            NativeName = "Deutsch"
                        },
                        new
                        {
                            LanguageId = 7,
                            Code = "ja",
                            EnglishName = "Japanese",
                            IsRightToLeft = false,
                            NativeName = "日本語"
                        },
                        new
                        {
                            LanguageId = 8,
                            Code = "zh",
                            EnglishName = "Mandarin Chinese",
                            IsRightToLeft = false,
                            NativeName = "普通话"
                        },
                        new
                        {
                            LanguageId = 9,
                            Code = "hi",
                            EnglishName = "Hindi",
                            IsRightToLeft = false,
                            NativeName = "हिन्दी"
                        },
                        new
                        {
                            LanguageId = 10,
                            Code = "pt",
                            EnglishName = "Portuguese",
                            IsRightToLeft = false,
                            NativeName = "Português"
                        },
                        new
                        {
                            LanguageId = 11,
                            Code = "ru",
                            EnglishName = "Russian",
                            IsRightToLeft = false,
                            NativeName = "Русский"
                        },
                        new
                        {
                            LanguageId = 12,
                            Code = "bn",
                            EnglishName = "Bengali",
                            IsRightToLeft = false,
                            NativeName = "বাংলা"
                        },
                        new
                        {
                            LanguageId = 13,
                            Code = "ko",
                            EnglishName = "Korean",
                            IsRightToLeft = false,
                            NativeName = "한국어"
                        },
                        new
                        {
                            LanguageId = 14,
                            Code = "it",
                            EnglishName = "Italian",
                            IsRightToLeft = false,
                            NativeName = "Italiano"
                        },
                        new
                        {
                            LanguageId = 15,
                            Code = "tr",
                            EnglishName = "Turkish",
                            IsRightToLeft = false,
                            NativeName = "Türkçe"
                        },
                        new
                        {
                            LanguageId = 16,
                            Code = "vi",
                            EnglishName = "Vietnamese",
                            IsRightToLeft = false,
                            NativeName = "Tiếng Việt"
                        },
                        new
                        {
                            LanguageId = 17,
                            Code = "te",
                            EnglishName = "Telugu",
                            IsRightToLeft = false,
                            NativeName = "తెలుగు"
                        },
                        new
                        {
                            LanguageId = 18,
                            Code = "mr",
                            EnglishName = "Marathi",
                            IsRightToLeft = false,
                            NativeName = "मराठी"
                        },
                        new
                        {
                            LanguageId = 19,
                            Code = "ta",
                            EnglishName = "Tamil",
                            IsRightToLeft = false,
                            NativeName = "தமிழ்"
                        },
                        new
                        {
                            LanguageId = 20,
                            Code = "ur",
                            EnglishName = "Urdu",
                            IsRightToLeft = true,
                            NativeName = "اردو"
                        },
                        new
                        {
                            LanguageId = 21,
                            Code = "el",
                            EnglishName = "Greek",
                            IsRightToLeft = false,
                            NativeName = "Ελληνικά"
                        },
                        new
                        {
                            LanguageId = 22,
                            Code = "nl",
                            EnglishName = "Dutch",
                            IsRightToLeft = false,
                            NativeName = "Nederlands"
                        },
                        new
                        {
                            LanguageId = 23,
                            Code = "sv",
                            EnglishName = "Swedish",
                            IsRightToLeft = false,
                            NativeName = "Svenska"
                        },
                        new
                        {
                            LanguageId = 24,
                            Code = "no",
                            EnglishName = "Norwegian",
                            IsRightToLeft = false,
                            NativeName = "Norsk"
                        },
                        new
                        {
                            LanguageId = 25,
                            Code = "pl",
                            EnglishName = "Polish",
                            IsRightToLeft = false,
                            NativeName = "Polski"
                        },
                        new
                        {
                            LanguageId = 26,
                            Code = "fi",
                            EnglishName = "Finnish",
                            IsRightToLeft = false,
                            NativeName = "Suomi"
                        },
                        new
                        {
                            LanguageId = 27,
                            Code = "cs",
                            EnglishName = "Czech",
                            IsRightToLeft = false,
                            NativeName = "Čeština"
                        },
                        new
                        {
                            LanguageId = 28,
                            Code = "hu",
                            EnglishName = "Hungarian",
                            IsRightToLeft = false,
                            NativeName = "Magyar"
                        },
                        new
                        {
                            LanguageId = 29,
                            Code = "th",
                            EnglishName = "Thai",
                            IsRightToLeft = false,
                            NativeName = "ไทย"
                        },
                        new
                        {
                            LanguageId = 30,
                            Code = "id",
                            EnglishName = "Indonesian",
                            IsRightToLeft = false,
                            NativeName = "Bahasa Indonesia"
                        },
                        new
                        {
                            LanguageId = 31,
                            Code = "ro",
                            EnglishName = "Romanian",
                            IsRightToLeft = false,
                            NativeName = "Română"
                        },
                        new
                        {
                            LanguageId = 32,
                            Code = "uk",
                            EnglishName = "Ukrainian",
                            IsRightToLeft = false,
                            NativeName = "Українська"
                        },
                        new
                        {
                            LanguageId = 33,
                            Code = "he",
                            EnglishName = "Hebrew",
                            IsRightToLeft = true,
                            NativeName = "עברית"
                        },
                        new
                        {
                            LanguageId = 34,
                            Code = "ms",
                            EnglishName = "Malay",
                            IsRightToLeft = false,
                            NativeName = "Bahasa Melayu"
                        },
                        new
                        {
                            LanguageId = 35,
                            Code = "fa",
                            EnglishName = "Persian",
                            IsRightToLeft = true,
                            NativeName = "فارسی"
                        },
                        new
                        {
                            LanguageId = 36,
                            Code = "sk",
                            EnglishName = "Slovak",
                            IsRightToLeft = false,
                            NativeName = "Slovenčina"
                        },
                        new
                        {
                            LanguageId = 37,
                            Code = "ca",
                            EnglishName = "Catalan",
                            IsRightToLeft = false,
                            NativeName = "Català"
                        });
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.LearningPath", b =>
                {
                    b.Property<int>("LearningPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Chapter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnownLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextLearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrevLearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LearningPathId");

                    b.HasIndex("KnownLanguageId");

                    b.HasIndex("NextLearningPathId");

                    b.HasIndex("PrevLearningPathId");

                    b.HasIndex("UserId");

                    b.HasIndex("TargetLanguageId", "KnownLanguageId", "Level", "Chapter")
                        .IsUnique();

                    b.ToTable("LearningPaths");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("KnownLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("KnownLanguageId");

                    b.HasIndex("TargetLanguageId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.UserExerciseType", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ExerciseTypeId");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("UserExerciseTypes");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.UserLanguage", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLearning")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("UserLanguages");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.UserProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LearningPathId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("practiseMistakesInThisPath")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "LearningPathId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("LearningPathId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.Exercise", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "KnownLanguage")
                        .WithMany()
                        .HasForeignKey("KnownLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.LearningPath", "LearningPath")
                        .WithMany("Exercises")
                        .HasForeignKey("LearningPathId");

                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseType");

                    b.Navigation("KnownLanguage");

                    b.Navigation("LearningPath");

                    b.Navigation("TargetLanguage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.LearningPath", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "KnownLanguage")
                        .WithMany()
                        .HasForeignKey("KnownLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.LearningPath", "NextLearningPath")
                        .WithMany()
                        .HasForeignKey("NextLearningPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AyalasLanguageAPI.Data.Model.LearningPath", "PrevLearningPath")
                        .WithMany()
                        .HasForeignKey("PrevLearningPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.User", "User")
                        .WithMany("LearningPaths")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KnownLanguage");

                    b.Navigation("NextLearningPath");

                    b.Navigation("PrevLearningPath");

                    b.Navigation("TargetLanguage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.Token", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.User", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "KnownLanguage")
                        .WithMany()
                        .HasForeignKey("KnownLanguageId");

                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "TargetLanguage")
                        .WithMany()
                        .HasForeignKey("TargetLanguageId");

                    b.Navigation("KnownLanguage");

                    b.Navigation("TargetLanguage");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.UserExerciseType", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.User", "User")
                        .WithMany("UserExerciseTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.UserLanguage", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.UserProgress", b =>
                {
                    b.HasOne("AyalasLanguageAPI.Data.Model.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId");

                    b.HasOne("AyalasLanguageAPI.Data.Model.LearningPath", "LearningPath")
                        .WithMany()
                        .HasForeignKey("LearningPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AyalasLanguageAPI.Data.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("LearningPath");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.LearningPath", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("AyalasLanguageAPI.Data.Model.User", b =>
                {
                    b.Navigation("LearningPaths");

                    b.Navigation("UserExerciseTypes");

                    b.Navigation("UserLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
