@hostname = localhost
@port = 5097
@host = http://{{hostname}}:{{port}}
@contentType = application/json
@userName = "johndoe"
@password = "SecurePassword123"

### Register a new user
# @name registerUser
POST {{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "displayName": "John Doe",
  "userName": {{userName}},
  "password": {{password}}
}

### login

# @name login
POST {{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "userName": {{userName}},
  "password": {{password}}
}

###

@token = {{login.response.body.token}}

### update profile - set display name, languages, and exercise types
POST {{host}}/api/profile
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "DisplayName": "John Doe 2",
  "languages": [
    {
      "languageId": 4,
      "isLearning": true
    },
    {
      "languageId": 1,
      "isLearning": false
    }
  ],
  "exerciseTypes": [
    {
      "exerciseTypeId": 1
    },
    {
      "exerciseTypeId": 2
    },
    {
      "exerciseTypeId": 3
    },
    {
      "exerciseTypeId": 4
    }
  ]
}

### get user profile
GET {{host}}/api/profile
Authorization: Bearer {{token}}

### get all available languages
GET {{host}}/api/static/languages
Authorization: Bearer {{token}}

### get current language
GET {{host}}/api/profile/current
Authorization: Bearer {{token}}

### switch current language
POST {{host}}/api/profile/current
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "TargetLanguageId": 4,
  "KnownLanguageId": 1
}

### Get the learning path for current language
### status 1 means it's done
GET {{host}}/api/learning/path
Authorization: Bearer {{token}}

### Update user progress to done for a specific learning path item
POST {{host}}/api/learning/progress
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 9
}

### Delete user progress for a specific learning path item (mark as not done)
DELETE {{host}}/api/learning/progress/9
Authorization: Bearer {{token}}

### Create a Learning Path
# @name createLearningPath1
POST {{host}}/api/creator/learning-path
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "languageId": 4,
  "level": 4,
  "chapter": 4,
  "name": "Nature",
  "prevLearningPathId": 10,
  "nextLearningPathId": 15
}
###
@newLearningPathId = {{createLearningPath1.response.body.learningPathId}}

### Create a Learning Path
POST {{host}}/api/creator/learning-path
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "languageId": 4,
  "level": 1,
  "chapter": 2,
  "name": "Nature",
  "prevLearningPathId": {{newLearningPathId}},
  "nextLearningPathId": 15
}

### Edit learning path
PUT {{host}}/api/creator/learning-path/10
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "level": 2,
  "chapter": 3,
  "name": "Outdoors"
}


### delete learning paths
DELETE {{host}}/api/creator/learning-path/14
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Create an Exercise for the Path created above
POST {{host}}/api/creator/exercise
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 10,
  "exerciseTypeId": 2,
  "data": "{\"question\": \"How do you say Hello?\", \"answer\": \"Hola\"}"
}

### Edit the Exercise created above
PUT {{host}}/api/creator/exercise/4
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "data": "{\"question\": \"How do you say Goodbye?\", \"answer\": \"Adiós\"}"
}

### Delete the Exercise created above
DELETE {{host}}/api/creator/exercise/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Get exercises for a learning path
GET {{host}}/api/learning/path/8/exercises
Authorization: Bearer {{token}}

### Logout
POST {{host}}/api/auth/logout
Authorization: Bearer {{token}}