@hostname = localhost
@port = 5097
@host = http://{{hostname}}:{{port}}
@contentType = application/json
@userName = "johndoe"
@password = "SecurePassword124"

### Register a new user
# @name registerUser
POST {{host}}/api/auth/register
Content-Type: {{contentType}}

{
  "displayName": "John Doe",
  "userName": {{userName}},
  "password": {{password}}
}

### login

# @name login
POST {{host}}/api/auth/login
Content-Type: {{contentType}}

{
  "userName": {{userName}},
  "password": {{password}}
}

###

@token = {{login.response.body.token}}

### auth me
GET {{host}}/api/auth/me
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Change password
POST {{host}}/api/auth/change-password
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "oldPassword": "SecurePassword123",
  "newPassword": "SecurePassword124"
}

### update profile - set display name, languages, and exercise types
POST {{host}}/api/profile
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "DisplayName": "John Doe 2",
  "languages": [
    {
      "languageId": 4,
      "isLearning": true
    },
    {
      "languageId": 1,
      "isLearning": false
    }
  ],
  "exerciseTypes": [
    {
      "exerciseTypeId": 1
    },
    {
      "exerciseTypeId": 2
    },
    {
      "exerciseTypeId": 3
    },
    {
      "exerciseTypeId": 4
    }
  ]
}

### get user profile
GET {{host}}/api/profile
Authorization: Bearer {{token}}

### get all available languages
GET {{host}}/api/static/languages
Authorization: Bearer {{token}}

### get current language
GET {{host}}/api/profile/current
Authorization: Bearer {{token}}

### switch current language
POST {{host}}/api/profile/current
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "TargetLanguageId": 4,
  "KnownLanguageId": 1
}

### Get the learning path for current language
### status 1 means it's done
GET {{host}}/api/learning/path
Authorization: Bearer {{token}}



### Create a Learning Path
# @name createLearningPath1
POST {{host}}/api/creator/learning-path
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "level": 1,
  "chapter": 1,
  "name": "Greetings"
}
###
@newLearningPathId = {{createLearningPath1.response.body.learningPathId}}

### Create a Learning Path
POST {{host}}/api/creator/learning-path
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "level": 1,
  "chapter": 2,
  "name": "Nature",
  "prevLearningPathId": {{newLearningPathId}}
}

### Update user progress to done for a specific learning path item
POST {{host}}/api/learning/progress
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 1
}

### Delete user progress for a specific learning path item (mark as not done)
DELETE {{host}}/api/learning/progress/1
Authorization: Bearer {{token}}

### Edit learning path
PUT {{host}}/api/creator/learning-path/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "level": 2,
  "chapter": 3,
  "name": "Outdoors"
}


### delete learning paths
DELETE {{host}}/api/creator/learning-path/2
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Create a simple Exercise for the Path created above
POST {{host}}/api/creator/exercise
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 1,
  "exerciseTypeId": 1,
  "data": "{\"KnownText\": \"How do you say Hello?\", \"TargetText\": \"Hvordan siger du hej?\"}"
}

### Create a simple Exercise for the Path created above
POST {{host}}/api/creator/exercise
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 1,
  "exerciseTypeId": 2,
  "data": "{\"KnownText\": \"How do you say Hello?\", \"TargetText\": \"Hvordan siger du hej?\"}"
}

### Edit the Exercise created above
PUT {{host}}/api/creator/exercise/1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "data": "{\"KnownText\": \"How do you say Goodbye?\", \"TargetText\": \"Adiós\"}"
}

### Create a fillin the blanks exercise for the Path created above
POST {{host}}/api/creator/exercise
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 1,
  "exerciseTypeId": 3,
  "data": "{\"TargetText\": \"Jeg bor __ Danmark, men jeg kommer __ Tyskland\", \"Replacements\": [\"i\", \"fra\"]}"
}

### Create a Matching Exercise for the Path created above
POST {{host}}/api/creator/exercise
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 1,
  "exerciseTypeId": 4,
  "data": "{\"Items\":[{\"TargetText\": \"Hvordan\", \"KnownText\": \"How\"}, {\"TargetText\": \"sier\", \"KnownText\": \"do you say\"}, {\"TargetText\": \"Hei?\", \"KnownText\": \"Hello?\"}, {\"TargetText\": \"Hva\", \"KnownText\": \"What\"}, {\"TargetText\": \"heter\", \"KnownText\": \"is your name?\"}, {\"TargetText\": \"du?\", \"KnownText\": \"you?\"}]}"
}

### Create a bucket list exercise for the Path created above
POST {{host}}/api/creator/exercise
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "learningPathId": 1,
  "exerciseTypeId": 5,
  "data": "{\"KnownText\": \"How do you say Hello?\", \"TargetText\": \"Hvordan siger du hej?\", \"ExtraOptions\": [\"ser\", \"farvel\", \"tak\"]}"
}

### Delete the Exercise created above
DELETE {{host}}/api/creator/exercise/1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Get exercises for a learning path
GET {{host}}/api/learning/path/1/exercises
Authorization: Bearer {{token}}

### Logout
POST {{host}}/api/auth/logout
Authorization: Bearer {{token}}