services:
  database:
    image: mysql:8.4.8
    container_name: langapp_mysql_instance
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PWD}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    command: --innodb_buffer_pool_size=256M --innodb_log_buffer_size=8M --max_connections=40 --key_buffer_size=16M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 60s

  api_app:
    image: langapp-language-api:latest
    container_name: langapp_backend_instance
    restart: always
    ports:
      - "${HOST_BIND_IP}:8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${STACK_ENV}
      - ASPNETCORE_HTTP_PORTS=8080
      - EmailConfirmation__ClientAddress=${CLIENT_ADDRESS}
      - EmailSettings__APIKey=${EMAIL_API_KEY}
      - ConnectionStrings__DefaultConnection=Server=database;Port=3306;Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_USER_PWD};
      - AllowedHosts=${ALLOWED_HOSTS}
    depends_on:
      database:
        condition: service_healthy # Instructs your API container to wait until the healthcheck returns green