# This extension block loads dynamically as an add-on configuration fragment
server {
    listen       443 ssl default_server;
    listen       [::]:443 ssl default_server;
    server_name  localhost;

    ssl_certificate      /etc/letsencrypt/live/ayalalangdemo.duckdns.org/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/ayalalangdemo.duckdns.org/privkey.pem;

    ssl_session_timeout  5m;
    ssl_protocols  TLSv1.2 TLSv1.3;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers   on;

    location / {
        proxy_pass         http://localhost:5000;
        proxy_http_version 1.1;
        
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}