import { Link } from "react-router-dom";
import { BRAND_NAME } from "../constants/learning";
import { FormHeader } from "./FormHeader";

export function WelcomeSnippet({ isPublic }: { isPublic: boolean }) {
  return (
    <>
      {
        !isPublic && (
          <FormHeader isPublic={false} title={`Welcome to ${BRAND_NAME}`} />
        ) || (
          <div className="form-row">
            <h1>Welcome to {BRAND_NAME}</h1>
          </div >
        )
      }
      <div className='form-row'>
        {BRAND_NAME} is a place to keep learning the language we have set to learn with ever more new exercises, as well as practice our previous mistakes.
      </div>
      <div className='form-row'>
        Generate a new language learning exercise in seconds, utilizing AI, and continue your learning, or go through the lessons already generated by others.
      </div>
      <div className="form-row">
        <Link className="home-link" to="/register">Register a new account</Link>, if you do not have one yet.
      </div>
      <div className="form-row">
        <Link className="home-link" to="/home">Login to {BRAND_NAME}</Link>. This link will redirect you to the app if you are already logged in.
      </div>
      <div className='form-row'>
        This app is also <Link className="home-link" to="/download-app">available on Android devices</Link>, through GitHub Releases.
      </div>
      <div className='form-row'>
        To discuss content creation, features and more, go to {BRAND_NAME}'s <Link className="home-link" to="https://discord.gg/UkzNfauGd">Discord server</Link>.
      </div>
      <div className='form-row'>
        To write to this app's creator and admin, use the <Link className="home-link" to="/contactus">Contact Us form</Link>.
      </div>
      <div className='form-row'>
        This web app is mobile friendly, but if you want to try out another rendition of it written in React Native, it is mounted <Link className="home-link" to="/mobile/" reloadDocument>here</Link>.
      </div>
      <div className='form-row'>
        One last gem: both the default web app and the /mobile/ endpoint have a "Fullscreen experience" installation option (a PWA app) from the main menu or pressing the Share button on iOS and then Add to Home Screen, after a successful login.
      </div>
    </>
  );
}