import { Link } from "react-router-dom";
import { BRAND_NAME } from "../constants/public";
import { FormHeader } from "./FormHeader";

export function WelcomeSnippet({ isPublic }: { isPublic: boolean }) {
  return (
    <>
      {
        !isPublic && (
          <FormHeader isPublic={false} title={`Welcome to ${BRAND_NAME}`} />
        ) || (
          <div className="form-row">
            <h1>Welcome to {BRAND_NAME}</h1>
          </div >
        )
      }
      <div className='form-row'>
        {BRAND_NAME} is a place to keep learning the language we have set to learn with ever more new exercises, as well as practice our previous mistakes.
      </div>
      <div className='form-row'>
        Generate a new language learning exercise in seconds, utilizing AI, and continue your learning, or go through the lessons already generated by others.
      </div>
      <div className="form-row">
        <Link className="home-link" to="/login">Login to {BRAND_NAME}</Link>. This link will redirect you to the app if you are already logged in.
      </div>
      <div className="form-row">
        <Link className="home-link" to="/register">Register a new account</Link>, if you do not have one yet.
      </div>
      <div className='form-row'>
        To discuss content creation, features and more, go to {BRAND_NAME}'s <Link className="home-link" to="https://discord.gg/UkzNfauGd">Discord server</Link>.
      </div>
      <div className='form-row'>
        To write to this app's admin, use the <Link className="home-link" to="/contactus">Contact Us form</Link>.
      </div>
    </>
  );
}